compressionLevel: mixed

enableGlobalCache: false

# Without this setting, the common package is hoisted in the root node_modules, causing the serverless-monorepo plugin to fail
nmHoistingLimits: workspaces

nodeLinker: node-modules
