version: "3.9"

services:
  mysql:
    image: mysql
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: hathor
    ports:
      - "3380:3306"
  unvoided_transaction:
    image: hathornetwork/hathor-core
    command: [
      "events_simulator",
      "--scenario", "UNVOIDED_TRANSACTION",
      "--seed", "1"
    ]
    ports:
      - "8081:8080"

networks:
  database:
