root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: 'module'
  project: './tsconfig.eslint.json'
env:
  node: true
  es6: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': off
overrides:
  - files:
      - 'src/**/*.ts'
    excludedFiles:
      - 'dist/*'
      - 'node_modules/*'
      - '__tests__/**/*.ts'
  - files:
      - "*.js"
    parser: "espree"
    parserOptions:
      ecmaVersion: 2022
      sourceType: 'module'
